name: mukhametdinov-final4

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure

  app:
    build: .
    container_name: app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

volumes:
  mysql_data: