version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: final4-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: world
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: