database:
  host: mysql
  port: 3306
  name: world
  username: user
  password: password
  timeout: 3000
  idle_test_period: 300
  min_pool_size: 2
  max_pool_size: 10

redis:
  host: redis
  port: 6379
  password: root
  timeout: 3000
  thread_pool_size: 3
  termination_await_sec: 5

general:
  check_quantity: 10
  check_pause_sec: 3